[build]
  command = "npx prisma generate && npx prisma db push --accept-data-loss && npx prisma db seed && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "false"
  PRISMA_GENERATE_DATAPROXY = "false"
